// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StaticCodeAnalyzer.Data;

#nullable disable

namespace StaticCodeAnalyzer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StaticCodeAnalyzer.Models.AnalysisExclusion", b =>
                {
                    b.Property<int>("ExclusionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExclusionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExclusionPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExclusionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("ExclusionId");

                    b.HasIndex("ProjectId");

                    b.ToTable("AnalysisExclusions");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.AnalysisResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResultId"));

                    b.Property<int?>("ColumnNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueSeverity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("RuleId")
                        .HasColumnType("integer");

                    b.Property<int>("ScanId")
                        .HasColumnType("integer");

                    b.Property<string>("SuggestedFix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ResultId");

                    b.HasIndex("FilePath");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RuleId");

                    b.HasIndex("ScanId");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.AnalysisRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RuleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RuleCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleSeverity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RuleId");

                    b.ToTable("AnalysisRules");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastScanned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.Scan", b =>
                {
                    b.Property<int>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScanId"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalLogPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalFilesScanned")
                        .HasColumnType("integer");

                    b.Property<int>("TotalIssuesFound")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScanId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StartTime");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.ScannedFile", b =>
                {
                    b.Property<int>("ScannedFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScannedFileId"));

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IssuesCount")
                        .HasColumnType("integer");

                    b.Property<int>("LinesCount")
                        .HasColumnType("integer");

                    b.Property<int>("ScanId")
                        .HasColumnType("integer");

                    b.HasKey("ScannedFileId");

                    b.HasIndex("ScanId");

                    b.ToTable("ScannedFiles");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.AnalysisExclusion", b =>
                {
                    b.HasOne("StaticCodeAnalyzer.Models.Project", "Project")
                        .WithMany("Exclusions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.AnalysisResult", b =>
                {
                    b.HasOne("StaticCodeAnalyzer.Models.Project", "Project")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaticCodeAnalyzer.Models.AnalysisRule", "Rule")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("RuleId");

                    b.HasOne("StaticCodeAnalyzer.Models.Scan", "Scan")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Rule");

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.Scan", b =>
                {
                    b.HasOne("StaticCodeAnalyzer.Models.Project", "Project")
                        .WithMany("Scans")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.ScannedFile", b =>
                {
                    b.HasOne("StaticCodeAnalyzer.Models.Scan", "Scan")
                        .WithMany("ScannedFiles")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.AnalysisRule", b =>
                {
                    b.Navigation("AnalysisResults");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.Project", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("Exclusions");

                    b.Navigation("Scans");
                });

            modelBuilder.Entity("StaticCodeAnalyzer.Models.Scan", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("ScannedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
